DROP DATABASE IF EXISTS Cloud;
CREATE DATABASE Cloud;

USE Cloud;
DROP TABLE IF EXISTS Tasks;
CREATE TABLE Tasks(
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    createdAt DATETIME,
    updatedAt DATETIME
);

DROP TABLE IF EXISTS Users;
CREATE TABLE Users(
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL,
    createdAt DATETIME NOT NULL,
    updatedAt DATETIME NOT NULL
);